"""Таблица списания + внешний ключ с именем

Revision ID: 71cc8ef07500
Revises: 
Create Date: 2025-06-06 17:20:42.902451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71cc8ef07500'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=False)
        
        batch_op.create_foreign_key('fk_maintenance_equipment_id', 'equipment', ['equipment_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance', schema=None) as batch_op:
        batch_op.drop_constraint('fk_maintenance_equipment_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'])
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
